In [55]:
import numpy as np 
import pandas as pd 

df = pd.read_csv("employees_100.csv")
df.head()
df.tail()

    employee_id         name department     city  ...  experience performance_score  projects_completed  joining_date
95          161  Nikhil Nair  MARKETING  Chennai  ...           0                 5                  22    2020-04-22
96          172   Neha Desai         HR  Chennai  ...           0                 5                   7    2020-11-14
97          115   Neha Reddy  Marketing  Chennai  ...          12                 4                  10    2019-06-06
98          193  Priya Nayak         HR      NaN  ...           3                 9                  16    2019-08-07
99          152  Kavya Joshi  Marketing    Delhi  ...          10                 7                   4    2022-03-25

[5 rows x 10 columns]

WHY DO WE NEED THIS 

Real world data is rarely clean . this is genuinely one of the largest parts of 
a Data anlyst or data scientist actual job - not the modeling this

 1-- Finding the missing values

In [56]:
df.isnull()
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [57]:
df2 = df.dropna()
df2

    employee_id          name    department       city  ...  experience performance_score  projects_completed  joining_date
0           184  Swati Kapoor  Data Science    Kolkata  ...           5                 5                   6    2021-07-02
2           171  Manish Desai  Data Science  Hyderabad  ...           0                 6                  18    2019-04-24
3           146      Neha Das   Engineering       Pune  ...           3                 8                   1    2022-12-13
5           140   Rahul Gupta         Sales  Hyderabad  ...           0                 9                  13    2018-12-27
6           123    Sneha Iyer            HR  Hyderabad  ...           4                 4                  18    2024-02-21
..          ...           ...           ...        ...  ...         ...               ...                 ...           ...
93          183  Deepak Nayak     Marketing  Hyderabad  ...           2                 5                  13    2020-08-09
94          121    Ashok Shah  Data Science       Pune  ...           4                 7                   7    2024-12-05
95          161   Nikhil Nair     MARKETING    Chennai  ...           0                 5                  22    2020-04-22
96          172    Neha Desai            HR    Chennai  ...           0                 5                   7    2020-11-14
99          152   Kavya Joshi     Marketing      Delhi  ...          10                 7                   4    2022-03-25

[71 rows x 10 columns]

In [58]:
df2.isnull().sum()
##THIS IS NOT A BEST WAY FOR DROPING THE VALUES

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [59]:
 ## what if we want to drop the value of city only 
df.dropna(subset=['city'])

    employee_id            name    department  ... performance_score  projects_completed joining_date
0           184    Swati Kapoor  Data Science  ...                 5                   6   2021-07-02
1           154  Kavya Malhotra   engineering  ...                 8                   8   2024-02-05
2           171    Manish Desai  Data Science  ...                 6                  18   2019-04-24
3           146        Neha Das   Engineering  ...                 8                   1   2022-12-13
5           140     Rahul Gupta         Sales  ...                 9                  13   2018-12-27
..          ...             ...           ...  ...               ...                 ...          ...
94          121      Ashok Shah  Data Science  ...                 7                   7   2024-12-05
95          161     Nikhil Nair     MARKETING  ...                 5                  22   2020-04-22
96          172      Neha Desai            HR  ...                 5                   7   2020-11-14
97          115      Neha Reddy     Marketing  ...                 4                  10   2019-06-06
99          152     Kavya Joshi     Marketing  ...                 7                   4   2022-03-25

[90 rows x 10 columns]

In [60]:
df.dropna(subset=['city' , 'age'])

    employee_id          name    department       city  ...  experience performance_score  projects_completed  joining_date
0           184  Swati Kapoor  Data Science    Kolkata  ...           5                 5                   6    2021-07-02
2           171  Manish Desai  Data Science  Hyderabad  ...           0                 6                  18    2019-04-24
3           146      Neha Das   Engineering       Pune  ...           3                 8                   1    2022-12-13
5           140   Rahul Gupta         Sales  Hyderabad  ...           0                 9                  13    2018-12-27
6           123    Sneha Iyer            HR  Hyderabad  ...           4                 4                  18    2024-02-21
..          ...           ...           ...        ...  ...         ...               ...                 ...           ...
94          121    Ashok Shah  Data Science       Pune  ...           4                 7                   7    2024-12-05
95          161   Nikhil Nair     MARKETING    Chennai  ...           0                 5                  22    2020-04-22
96          172    Neha Desai            HR    Chennai  ...           0                 5                   7    2020-11-14
97          115    Neha Reddy     Marketing    Chennai  ...          12                 4                  10    2019-06-06
99          152   Kavya Joshi     Marketing      Delhi  ...          10                 7                   4    2022-03-25

[84 rows x 10 columns]

In [61]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [62]:
df['age'].fillna(df['age'] .mean(),inplace = True)

C:\Users\samee\AppData\Local\Temp\ipykernel_32312\4119420743.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'] .mean(),inplace = True)

In [63]:
df.isnull().sum()
##now age is filled with mean

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [64]:
# df['salary'] = df['salary'].str.replace(" , " , "",regex= False)
# df['salary'] = df['salary'].astype(int) it does not convert the null values to an integer 
# df['salary'].fillna(df['salary'].median() , inplace = True)

In [65]:
df['salary'] = df['salary'].str.replace(",", "" , regex=False)
df['salary'] = pd.to_numeric(df['salary'] , errors='coerce')##coerce means skip krna 
df['salary'] = df['salary'].fillna(df['salary'].median())

In [66]:
df['salary'].dtype

dtype('float64')

In [67]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

for department (string)

In [68]:
df['department'].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [73]:
df['department'] = df['department'].fillna(df['department'].mode()[0])
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [74]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

DUPLICATE

In [75]:
df.duplicated().sum()

np.int64(0)

In [76]:
df = df.reset_index()

In [77]:
df.head()

   index  employee_id            name    department  ... experience  performance_score  projects_completed  joining_date
0      0          184    Swati Kapoor  Data Science  ...          5                  5                   6    2021-07-02
1      1          154  Kavya Malhotra   engineering  ...          1                  8                   8    2024-02-05
2      2          171    Manish Desai  Data Science  ...          0                  6                  18    2019-04-24
3      3          146        Neha Das   Engineering  ...          3                  8                   1    2022-12-13
4      4          145       Isha Nair  Data Science  ...          8                  8                  14    2019-11-25

[5 rows x 11 columns]

In [78]:
df.duplicated(subset=["employee_id"]).sum()

np.int64(4)

In [79]:
df.drop_duplicates(subset=["employee_id"] , keep="first")

    index  employee_id            name    department  ... experience  performance_score  projects_completed  joining_date
0       0          184    Swati Kapoor  Data Science  ...          5                  5                   6    2021-07-02
1       1          154  Kavya Malhotra   engineering  ...          1                  8                   8    2024-02-05
2       2          171    Manish Desai  Data Science  ...          0                  6                  18    2019-04-24
3       3          146        Neha Das   Engineering  ...          3                  8                   1    2022-12-13
4       4          145       Isha Nair  Data Science  ...          8                  8                  14    2019-11-25
..    ...          ...             ...           ...  ...        ...                ...                 ...           ...
95     95          161     Nikhil Nair     MARKETING  ...          0                  5                  22    2020-04-22
96     96          172      Neha Desai            HR  ...          0                  5                   7    2020-11-14
97     97          115      Neha Reddy     Marketing  ...         12                  4                  10    2019-06-06
98     98          193     Priya Nayak            HR  ...          3                  9                  16    2019-08-07
99     99          152     Kavya Joshi     Marketing  ...         10                  7                   4    2022-03-25

[96 rows x 11 columns]

In [85]:
df["joining_date"] = pd.to_datetime(df["joining_date"])
df

    index  employee_id            name    department  ... experience  performance_score  projects_completed  joining_date
0       0          184    Swati Kapoor  Data Science  ...          5                  5                   6    2021-07-02
1       1          154  Kavya Malhotra   engineering  ...          1                  8                   8    2024-02-05
2       2          171    Manish Desai  Data Science  ...          0                  6                  18    2019-04-24
3       3          146        Neha Das   Engineering  ...          3                  8                   1    2022-12-13
4       4          145       Isha Nair  Data Science  ...          8                  8                  14    2019-11-25
..    ...          ...             ...           ...  ...        ...                ...                 ...           ...
95     95          161     Nikhil Nair     MARKETING  ...          0                  5                  22    2020-04-22
96     96          172      Neha Desai            HR  ...          0                  5                   7    2020-11-14
97     97          115      Neha Reddy     Marketing  ...         12                  4                  10    2019-06-06
98     98          193     Priya Nayak            HR  ...          3                  9                  16    2019-08-07
99     99          152     Kavya Joshi     Marketing  ...         10                  7                   4    2022-03-25

[100 rows x 11 columns]

RENAMING the data 

rename the column spelling

In [94]:
df.rename(columns={"name" : "employee_name"} , inplace= True )

In [95]:
df

    index  employee_id   employee_name    department  ... experience  performance_score  projects_completed  joining_date
0       0          184    Swati Kapoor  Data Science  ...          5                  5                   6    2021-07-02
1       1          154  Kavya Malhotra   engineering  ...          1                  8                   8    2024-02-05
2       2          171    Manish Desai  Data Science  ...          0                  6                  18    2019-04-24
3       3          146        Neha Das   Engineering  ...          3                  8                   1    2022-12-13
4       4          145       Isha Nair  Data Science  ...          8                  8                  14    2019-11-25
..    ...          ...             ...           ...  ...        ...                ...                 ...           ...
95     95          161     Nikhil Nair     MARKETING  ...          0                  5                  22    2020-04-22
96     96          172      Neha Desai            HR  ...          0                  5                   7    2020-11-14
97     97          115      Neha Reddy     Marketing  ...         12                  4                  10    2019-06-06
98     98          193     Priya Nayak            HR  ...          3                  9                  16    2019-08-07
99     99          152     Kavya Joshi     Marketing  ...         10                  7                   4    2022-03-25

[100 rows x 11 columns]

In [98]:
df.columns = df.columns.str.strip().str.lower().str.replace("_" , " " )

In [99]:
df

    index  employee id   employee name    department  ... experience  performance score  projects completed  joining date
0       0          184    Swati Kapoor  Data Science  ...          5                  5                   6    2021-07-02
1       1          154  Kavya Malhotra   engineering  ...          1                  8                   8    2024-02-05
2       2          171    Manish Desai  Data Science  ...          0                  6                  18    2019-04-24
3       3          146        Neha Das   Engineering  ...          3                  8                   1    2022-12-13
4       4          145       Isha Nair  Data Science  ...          8                  8                  14    2019-11-25
..    ...          ...             ...           ...  ...        ...                ...                 ...           ...
95     95          161     Nikhil Nair     MARKETING  ...          0                  5                  22    2020-04-22
96     96          172      Neha Desai            HR  ...          0                  5                   7    2020-11-14
97     97          115      Neha Reddy     Marketing  ...         12                  4                  10    2019-06-06
98     98          193     Priya Nayak            HR  ...          3                  9                  16    2019-08-07
99     99          152     Kavya Joshi     Marketing  ...         10                  7                   4    2022-03-25

[100 rows x 11 columns]