In [3]:
import pandas as pd 
df = pd.read_csv("sales_data - sales_data.csv")
df

     Order_ID        Date Region     Category      Product  ...     Sales      Cost    Profit  Customer_Type  Payment_Method
0           1  2025-05-06   East  Electronics       Laptop  ...   5925.68   3441.33   2484.35     Individual   Bank Transfer
1           2  2025-04-22  North  Electronics       Laptop  ...  20412.08  11389.14   9022.94     Individual   Bank Transfer
2           3  2025-01-04   East    Furniture        Table  ...  21034.74  13716.23   7318.51     Individual            Card
3           4  2025-07-14  North     Clothing      T-Shirt  ...   7307.80   4773.36   2534.44       Business            Cash
4           5  2025-07-13  North      Grocery  Cooking Oil  ...   8347.80   6668.40   1679.40       Business            Card
..        ...         ...    ...          ...          ...  ...       ...       ...       ...            ...             ...
245       246  2025-10-22  South   Stationery       Marker  ...  31993.50  25011.29   6982.21       Business            Card
246       247  2025-07-31  South     Clothing        Jeans  ...  14120.10  10124.33   3995.77     Individual   Bank Transfer
247       248  2025-06-26  North   Stationery         File  ...  51216.49  33066.41  18150.08       Business   Bank Transfer
248       249  2025-04-05   West    Furniture    Bookshelf  ...  43090.56  34679.38   8411.18       Business            Card
249       250  2025-08-02   West      Grocery         Rice  ...  48122.28  32074.74  16047.54       Business            Card

[250 rows x 12 columns]

In [4]:
df.head()

   Order_ID        Date Region     Category      Product  ...     Sales      Cost   Profit  Customer_Type  Payment_Method
0         1  2025-05-06   East  Electronics       Laptop  ...   5925.68   3441.33  2484.35     Individual   Bank Transfer
1         2  2025-04-22  North  Electronics       Laptop  ...  20412.08  11389.14  9022.94     Individual   Bank Transfer
2         3  2025-01-04   East    Furniture        Table  ...  21034.74  13716.23  7318.51     Individual            Card
3         4  2025-07-14  North     Clothing      T-Shirt  ...   7307.80   4773.36  2534.44       Business            Cash
4         5  2025-07-13  North      Grocery  Cooking Oil  ...   8347.80   6668.40  1679.40       Business            Card

[5 rows x 12 columns]

In [6]:
df.tail()

     Order_ID        Date Region    Category    Product  ...     Sales      Cost    Profit  Customer_Type  Payment_Method
245       246  2025-10-22  South  Stationery     Marker  ...  31993.50  25011.29   6982.21       Business            Card
246       247  2025-07-31  South    Clothing      Jeans  ...  14120.10  10124.33   3995.77     Individual   Bank Transfer
247       248  2025-06-26  North  Stationery       File  ...  51216.49  33066.41  18150.08       Business   Bank Transfer
248       249  2025-04-05   West   Furniture  Bookshelf  ...  43090.56  34679.38   8411.18       Business            Card
249       250  2025-08-02   West     Grocery       Rice  ...  48122.28  32074.74  16047.54       Business            Card

[5 rows x 12 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        250 non-null    int64
 1   Date            250 non-null    object
 2   Region          250 non-null    object
 3   Category        250 non-null    object
 4   Product         250 non-null    object
 5   Quantity        250 non-null    int64
 6   Unit_Price      250 non-null    float64
 7   Sales           250 non-null    float64
 8   Cost            250 non-null    float64
 9   Profit          250 non-null    float64
 10  Customer_Type   250 non-null    object
 11  Payment_Method  250 non-null    object
dtypes: float64(4), int64(2), object(6)
memory usage: 23.6+ KB

In [8]:
df.describe()

         Order_ID    Quantity   Unit_Price         Sales          Cost        Profit
count  250.000000  250.000000   250.000000    250.000000    250.000000    250.000000
mean   125.500000   11.052000  2601.302480  28418.620880  19867.392760   8551.228120
std     72.312977    5.752012  1380.118132  22491.283759  16068.799785   7384.171569
min      1.000000    1.000000    85.590000    603.780000    503.260000    100.520000
25%     63.250000    6.000000  1411.500000   9264.647500   6704.377500   2595.530000
50%    125.500000   11.000000  2709.520000  22019.905000  15997.785000   6812.940000
75%    187.750000   16.000000  3743.237500  42019.557500  29263.552500  11955.045000
max    250.000000   20.000000  4980.050000  87440.400000  66786.640000  37200.550000

In [12]:
df.isnull()

     Order_ID   Date  Region  Category  Product  ...  Sales   Cost  Profit  Customer_Type  Payment_Method
0       False  False   False     False    False  ...  False  False   False          False           False
1       False  False   False     False    False  ...  False  False   False          False           False
2       False  False   False     False    False  ...  False  False   False          False           False
3       False  False   False     False    False  ...  False  False   False          False           False
4       False  False   False     False    False  ...  False  False   False          False           False
..        ...    ...     ...       ...      ...  ...    ...    ...     ...            ...             ...
245     False  False   False     False    False  ...  False  False   False          False           False
246     False  False   False     False    False  ...  False  False   False          False           False
247     False  False   False     False    False  ...  False  False   False          False           False
248     False  False   False     False    False  ...  False  False   False          False           False
249     False  False   False     False    False  ...  False  False   False          False           False

[250 rows x 12 columns]

In [17]:
df.isnull().sum()

Order_ID          0
Date              0
Region            0
Category          0
Product           0
Quantity          0
Unit_Price        0
Sales             0
Cost              0
Profit            0
Customer_Type     0
Payment_Method    0
dtype: int64

In [26]:
df[["Sales", "Profit"]].head()

      Sales   Profit
0   5925.68  2484.35
1  20412.08  9022.94
2  21034.74  7318.51
3   7307.80  2534.44
4   8347.80  1679.40

In [27]:
df

     Order_ID        Date Region     Category      Product  ...     Sales      Cost    Profit  Customer_Type  Payment_Method
0           1  2025-05-06   East  Electronics       Laptop  ...   5925.68   3441.33   2484.35     Individual   Bank Transfer
1           2  2025-04-22  North  Electronics       Laptop  ...  20412.08  11389.14   9022.94     Individual   Bank Transfer
2           3  2025-01-04   East    Furniture        Table  ...  21034.74  13716.23   7318.51     Individual            Card
3           4  2025-07-14  North     Clothing      T-Shirt  ...   7307.80   4773.36   2534.44       Business            Cash
4           5  2025-07-13  North      Grocery  Cooking Oil  ...   8347.80   6668.40   1679.40       Business            Card
..        ...         ...    ...          ...          ...  ...       ...       ...       ...            ...             ...
245       246  2025-10-22  South   Stationery       Marker  ...  31993.50  25011.29   6982.21       Business            Card
246       247  2025-07-31  South     Clothing        Jeans  ...  14120.10  10124.33   3995.77     Individual   Bank Transfer
247       248  2025-06-26  North   Stationery         File  ...  51216.49  33066.41  18150.08       Business   Bank Transfer
248       249  2025-04-05   West    Furniture    Bookshelf  ...  43090.56  34679.38   8411.18       Business            Card
249       250  2025-08-02   West      Grocery         Rice  ...  48122.28  32074.74  16047.54       Business            Card

[250 rows x 12 columns]

In [28]:
df[df["Region"] == "South"].head()

    Order_ID        Date Region     Category      Product  ...     Sales      Cost    Profit  Customer_Type  Payment_Method
5          6  2025-05-29  South  Electronics       Laptop  ...  12851.46  10408.98   2442.48       Business             UPI
6          7  2025-07-09  South      Grocery          Tea  ...  13044.72   8219.39   4825.33     Individual            Card
7          8  2025-08-25  South   Stationery          Pen  ...  18021.12  14914.59   3106.53     Individual             UPI
13        14  2025-08-21  South     Clothing        Shoes  ...   4771.39   3877.98    893.41       Business            Card
17        18  2025-05-16  South      Grocery  Cooking Oil  ...  74265.18  50273.17  23992.01     Individual            Card

[5 rows x 12 columns]

In [31]:
df[df["Product"] == "Laptop"].head(10)

     Order_ID        Date Region     Category Product  ...     Sales      Cost    Profit  Customer_Type  Payment_Method
0           1  2025-05-06   East  Electronics  Laptop  ...   5925.68   3441.33   2484.35     Individual   Bank Transfer
1           2  2025-04-22  North  Electronics  Laptop  ...  20412.08  11389.14   9022.94     Individual   Bank Transfer
5           6  2025-05-29  South  Electronics  Laptop  ...  12851.46  10408.98   2442.48       Business             UPI
20         21  2025-02-06   East  Electronics  Laptop  ...  20878.04  15673.01   5205.03     Individual            Card
28         29  2025-09-15   West  Electronics  Laptop  ...  14097.93  11817.36   2280.57     Individual            Card
64         65  2025-05-07  North  Electronics  Laptop  ...  29429.26  21671.73   7757.53     Individual            Card
74         75  2025-04-24   East  Electronics  Laptop  ...  45166.55  28990.68  16175.87       Business   Bank Transfer
87         88  2025-06-07  South  Electronics  Laptop  ...  75146.80  54162.97  20983.83       Business   Bank Transfer
129       130  2025-07-25   West  Electronics  Laptop  ...  48246.52  33631.72  14614.80       Business            Cash
202       203  2025-07-16   East  Electronics  Laptop  ...  42395.40  35561.51   6833.89     Individual             UPI

[10 rows x 12 columns]

In [40]:
df[df["Sales"]>10000].head(10)

    Order_ID        Date Region     Category     Product  ...     Sales      Cost    Profit  Customer_Type  Payment_Method
1          2  2025-04-22  North  Electronics      Laptop  ...  20412.08  11389.14   9022.94     Individual   Bank Transfer
2          3  2025-01-04   East    Furniture       Table  ...  21034.74  13716.23   7318.51     Individual            Card
5          6  2025-05-29  South  Electronics      Laptop  ...  12851.46  10408.98   2442.48       Business             UPI
6          7  2025-07-09  South      Grocery         Tea  ...  13044.72   8219.39   4825.33     Individual            Card
7          8  2025-08-25  South   Stationery         Pen  ...  18021.12  14914.59   3106.53     Individual             UPI
8          9  2025-06-11  North  Electronics  Smartphone  ...  17879.16  10965.20   6913.96       Business            Card
10        11  2025-04-23   East   Stationery        File  ...  12860.80   7424.19   5436.61     Individual            Cash
12        13  2025-12-16  North   Stationery    Notebook  ...  67803.30  52925.87  14877.43       Business            Cash
14        15  2025-11-24   East   Stationery    Notebook  ...  52094.80  31040.78  21054.02     Individual            Cash
15        16  2025-01-10   West   Stationery      Marker  ...  18596.16  15130.14   3466.02       Business            Card

[10 rows x 12 columns]

In [41]:
df.groupby("Region")["Sales"].sum()

Region
East     1677530.43
North    1779493.08
South    1506044.32
West     2141587.39
Name: Sales, dtype: float64

In [49]:
df2 = df.groupby("Product")["Sales"].sum()
df2

Product
Bookshelf       285559.60
Cabinet          16654.08
Coffee          237809.40
Cooking Oil     195909.47
Desk            211292.89
File            428035.88
Headphones      178862.89
Jacket          188573.63
Jeans           343257.58
Keyboard        474738.36
Laptop          387076.22
Marker          223323.54
Monitor         372109.76
Notebook        311460.54
Office Chair    146477.25
Pen             103357.85
Rice            429216.22
Shirt           275648.56
Shoes           320738.75
Smartphone      313258.48
Stapler         260070.15
Sugar           197491.50
T-Shirt         301644.51
Table           543991.25
Tea             358096.86
Name: Sales, dtype: float64

In [ ]:
df

In [1]:
df["Laptop"]
df
df.groupby("Product" == "Laptop)["Sales"].sum()

SyntaxError: unterminated string literal (detected at line 3) (4072580954.py, line 3)

In [2]:
import pandas as pd 
df = pd.read_csv("student_info - student_info.csv")
print(df)

    Student_ID          Name   Age  Gender    Department  Semester  \
0       STU001  Arjun Sharma   NaN  Female  Data Science         4
1       STU002  Arjun Shetty  24.0  Female           ISE         2
2       STU003   Aarav Reddy  21.0    Male           CSE         8
3       STU004    Rahul Nair  21.0  Female           CSE         6
4       STU005  Ananya Singh  21.0    Male           EEE         2
..         ...           ...   ...     ...           ...       ...
250     STU149   Kiran Joshi  25.0  Female    Mechanical         4
251     STU220  Vivaan Gupta  19.0    Male           NaN         7
252     STU095   Kiran Joshi  19.0  Female    Mechanical         2
253     STU085    Ananya Rao  23.0  Female           ISE         6
254     STU004    Rahul Nair  21.0  Female           CSE         6

     Attendance_Percentage  Internal_Marks  CGPA       City Scholarship
0                     97.8            42.0  7.79  Mangaluru         Yes
1                     62.0            21.7  9.26    Chennai         Yes
2                     86.9            20.6  9.83  Mangaluru          No
3                     64.6            25.5  5.51   Hubballi          No
4                     78.6            33.0  6.10     Mysuru         Yes
..                     ...             ...   ...        ...         ...
250                   70.6            46.9  7.11   Belagavi          No
251                   84.7            20.8  5.72   Belagavi          No
252                   56.0             NaN  6.05   Tumakuru         Yes
253                   86.7            34.2  5.04   Hubballi         Yes
254                   64.6            25.5  5.51   Hubballi          No

[255 rows x 11 columns]

In [4]:
df.head(20)

   Student_ID             Name   Age  Gender  ... Internal_Marks  CGPA       City  Scholarship
0      STU001     Arjun Sharma   NaN  Female  ...           42.0  7.79  Mangaluru          Yes
1      STU002     Arjun Shetty  24.0  Female  ...           21.7  9.26    Chennai          Yes
2      STU003      Aarav Reddy  21.0    Male  ...           20.6  9.83  Mangaluru           No
3      STU004       Rahul Nair  21.0  Female  ...           25.5  5.51   Hubballi           No
4      STU005     Ananya Singh  21.0    Male  ...           33.0  6.10     Mysuru          Yes
5      STU006     Aadhya Reddy  20.0    Male  ...            NaN  6.51   Tumakuru          Yes
6      STU007       Kavya Iyer  23.0    Male  ...           26.0  7.33     Mysuru          NaN
7      STU008       Riya Naidu  25.0  Female  ...           38.2   NaN     Mysuru          Yes
8      STU009      Rahul Joshi  24.0    Male  ...           49.0  8.95  Mangaluru          Yes
9      STU010     Aadhya Singh  18.0    Male  ...           40.5  6.92        NaN           No
10     STU011       Diya Patel  24.0  Female  ...           21.0  9.50   Hubballi          Yes
11     STU012         Sai Nair  21.0    Male  ...           29.4  7.36   Belagavi          Yes
12     STU013   Rahul Kulkarni  19.0    Male  ...           49.1  8.76    Chennai           No
13     STU014     Aditya Patel  19.0  Female  ...           37.9  9.57  Mangaluru           No
14     STU015     Aadhya Naidu  25.0  Female  ...           21.4  6.29   Hubballi           No
15     STU016     Vihaan Patel  25.0  Female  ...           44.9  6.46    Chennai           No
16     STU017       Diya Patel  21.0   Other  ...           24.2  8.91  Hyderabad          Yes
17     STU018  Vivaan Kulkarni  18.0    Male  ...           43.2  5.59    Chennai          Yes
18     STU019     Aadhya Gupta  25.0  Female  ...           41.2  8.51   Tumakuru          Yes
19     STU020     Arjun Shetty  18.0  Female  ...           30.8  5.14   Belagavi          Yes

[20 rows x 11 columns]

In [13]:
df[df["Age"].notna()].head(100).isnull().sum()

Student_ID                0
Name                      0
Age                       0
Gender                    6
Department                6
Semester                  0
Attendance_Percentage    11
Internal_Marks            9
CGPA                      8
City                      6
Scholarship               9
dtype: int64

In [16]:
df.isnull().values.all()## false
df.isnull().values.any() ## true

np.False_

In [21]:
(df.isnull().sum() / len(df)) *100

Student_ID               0.000000
Name                     0.000000
Age                      4.705882
Gender                   3.921569
Department               5.882353
Semester                 0.000000
Attendance_Percentage    7.843137
Internal_Marks           7.450980
CGPA                     6.274510
City                     4.705882
Scholarship              5.882353
dtype: float64

In [28]:
df[df.isnull().any(axis=1)]

    Student_ID            Name   Age  Gender  ... Internal_Marks  CGPA       City  Scholarship
0       STU001    Arjun Sharma   NaN  Female  ...           42.0  7.79  Mangaluru          Yes
5       STU006    Aadhya Reddy  20.0    Male  ...            NaN  6.51   Tumakuru          Yes
6       STU007      Kavya Iyer  23.0    Male  ...           26.0  7.33     Mysuru          NaN
7       STU008      Riya Naidu  25.0  Female  ...           38.2   NaN     Mysuru          Yes
9       STU010    Aadhya Singh  18.0    Male  ...           40.5  6.92        NaN           No
..         ...             ...   ...     ...  ...            ...   ...        ...          ...
246     STU247      Rahul Iyer  18.0    Male  ...            NaN  6.89  Mangaluru           No
248     STU249    Sai Kulkarni  23.0    Male  ...           30.8   NaN   Tumakuru          Yes
249     STU250  Priya Kulkarni  20.0    Male  ...           48.5   NaN        NaN           No
251     STU220    Vivaan Gupta  19.0    Male  ...           20.8  5.72   Belagavi           No
252     STU095     Kiran Joshi  19.0  Female  ...            NaN  6.05   Tumakuru          Yes

[98 rows x 11 columns]

In [47]:
df([df["CGPA", "Age"]).isnull()

AttributeError: 'DataFrameGroupBy' object has no attribute 'isnull'