In [82]:
import numpy as np 
import pandas as pd 
df = pd.read_csv("employees_100.csv")
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [83]:
df.head()
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['city'].unique()

array(['Kolkata', 'Mumbai', 'Hyderabad', 'Pune', nan, 'Delhi',
       'Bangalore', 'Chennai'], dtype=object)

In [84]:
df['department'].nunique()

13

In [85]:
df.groupby("city")['salary'].mean()

city
Bangalore    69652.000000
Chennai      64847.571429
Delhi        65486.916667
Hyderabad    61321.562500
Kolkata      64820.769231
Mumbai       65678.000000
Pune         62908.307692
Name: salary, dtype: float64

In [86]:
df.groupby("city")

In [87]:
df.groupby("city")['salary'].max()
df.groupby("city")['age'].min()
df.groupby("city")['age'].median()

city
Bangalore    34.5
Chennai      28.0
Delhi        34.0
Hyderabad    31.0
Kolkata      26.0
Mumbai       27.0
Pune         32.0
Name: age, dtype: float64

In [88]:
df.groupby(['department','city'])['salary'].mean()

department    city
 Finance      Bangalore             NaN
 HR           Hyderabad    59273.000000
 Marketing    Hyderabad    55295.000000
Data Science  Bangalore             NaN
              Delhi        76267.000000
              Hyderabad    78145.500000
              Kolkata      72303.000000
              Mumbai       78465.000000
              Pune         75498.000000
Engineering   Bangalore    79164.500000
              Chennai      72065.333333
              Delhi        80358.000000
              Hyderabad    84870.000000
              Kolkata      75226.000000
              Mumbai                NaN
              Pune         74269.000000
FINANCE       Chennai      71889.000000
Finance       Bangalore    71062.000000
              Delhi        66422.000000
              Hyderabad    67464.000000
              Kolkata      58998.750000
              Mumbai       64112.000000
              Pune         61267.000000
HR            Bangalore    59591.000000
              Chennai      52250.000000
              Delhi        59456.000000
              Hyderabad    55353.250000
              Kolkata      55542.000000
              Pune         54148.666667
MARKETING     Chennai      55740.000000
Marketing     Bangalore    62038.500000
              Chennai               NaN
              Delhi        62910.000000
              Hyderabad    57429.666667
              Kolkata      59186.000000
              Mumbai       60785.500000
              Pune         58481.000000
SALES         Hyderabad             NaN
Sales         Chennai      57858.000000
              Delhi        66095.000000
              Hyderabad    52488.500000
              Kolkata      60015.000000
              Mumbai       52862.000000
engineering   Kolkata      84255.000000
              Mumbai       77058.000000
Name: salary, dtype: float64

In [89]:
## multiple col at once 
df.groupby("department")[["salary" , "performance_score" ]].mean()

                    salary  performance_score
department
 Finance               NaN           4.000000
 HR           59273.000000           6.500000
 Marketing    55295.000000           7.000000
Data Science  76849.555556           5.700000
Engineering   76351.700000           5.214286
FINANCE       71889.000000           5.000000
Finance       65083.642857           5.437500
HR            56131.533333           5.941176
MARKETING     55740.000000           5.000000
Marketing     59222.785714           5.882353
SALES                  NaN           7.000000
Sales         58271.714286           6.500000
engineering   76634.666667           8.000000

In [90]:
## multiple aggregation with agg()
df.groupby("department").agg({
    "salary" : ["mean" , "max"] ,
    "performance_score" : "mean" , 
    "employee_id" : "count"
    
})

                    salary          performance_score employee_id
                      mean      max              mean       count
department
 Finance               NaN      NaN          4.000000           1
 HR           59273.000000  59273.0          6.500000           2
 Marketing    55295.000000  55295.0          7.000000           1
Data Science  76849.555556  88216.0          5.700000          10
Engineering   76351.700000  84870.0          5.214286          14
FINANCE       71889.000000  71889.0          5.000000           1
Finance       65083.642857  80597.0          5.437500          16
HR            56131.533333  66363.0          5.941176          17
MARKETING     55740.000000  55740.0          5.000000           1
Marketing     59222.785714  69499.0          5.882353          17
SALES                  NaN      NaN          7.000000           1
Sales         58271.714286  68490.0          6.500000           8
engineering   76634.666667  84255.0          8.000000           3

In [92]:
department_summary = df.groupby("department").agg(
    average_salary = ("salary" , "mean") ,
    highest_salary = ("salary" , "max") , 
    employee_count = ("employee_id","count")
     
)
department_summary

              average_salary  highest_salary  employee_count
department
 Finance                 NaN             NaN               1
 HR             59273.000000         59273.0               2
 Marketing      55295.000000         55295.0               1
Data Science    76849.555556         88216.0              10
Engineering     76351.700000         84870.0              14
FINANCE         71889.000000         71889.0               1
Finance         65083.642857         80597.0              16
HR              56131.533333         66363.0              17
MARKETING       55740.000000         55740.0               1
Marketing       59222.785714         69499.0              17
SALES                    NaN             NaN               1
Sales           58271.714286         68490.0               8
engineering     76634.666667         84255.0               3