WHY DO WE NEED THI S

Analysis isn't only reading existing columns — often you're creating new information from what's already there. This is exactly what "feature engineering" means in Machine Learning: existing features, transformed into new ones.

Creating and modyfying COLUMNS directly

In [40]:
import numpy as np 
import pandas as pd 

df = pd.read_csv("employees_100.csv")
df.head()
df.duplicated(subset=["employee_id"]).sum()
df.drop_duplicates(subset=["employee_id"],keep="first",inplace=True)

In [41]:
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')

df['annual_salary'] = df['salary'] * 12

df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0

In [42]:
def categorize(num):
    if(num>5):
        return "Experienced candidate"
    elif num<= 5:
        return "learner"

##using the lambda function 

## when we have single condition so we can use this 

# df["salary_level"] = df["salary"].apply(
#     lambda salary: "High" if salary > 70000 else "Normal"
# )

In [43]:
df['experience_status'] = df['experience'].apply(categorize)
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,learner
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,learner
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,learner
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,learner
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate

In [44]:
## T