WHY DO WE NEED PANDA

In [40]:
import numpy as np 
import pandas as pd

Get a data set

In [41]:
a = [1,2,3,4,5,6] ## list

In [42]:
## converting list into a series 
s = pd.Series(a)
s
s[1]

np.int64(2)

In [43]:
d = {"Aman" : 68, "rohan":34, "Akarsh" : 89}
s = pd.Series(d)
s

Aman      68
rohan     34
Akarsh    89
dtype: int64

In [44]:
df = pd.DataFrame([d])
df
#creeating a series with lables

# marks = pd.Series(
#     ["Rithvik",49,46.5],
#     index = ["Ram","Ravi","Sam"]
# )
# marks

   Aman  rohan  Akarsh
0    68     34      89

In [46]:
df = pd.DataFrame({
    "Name":["Aman","Riya"],
    "salary":[10000,500000]
})
df 
data = pd.DataFrame({
    "Name":["Sourabh" , "Qaasim"],
    "Salary" : [90000 , 3332242]
})
df = pd.DataFrame(data)
df

      Name   Salary
0  Sourabh    90000
1   Qaasim  3332242

In [48]:
df.columns
df.shape

(2, 2)

LOAD DATA IN CSV FILE

In [15]:
df = pd.read_csv("employees_100.csv")
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [51]:
df.head() ## SHOWS STARTING 5

      Name   Salary
0  Sourabh    90000
1   Qaasim  3332242

In [17]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [18]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
40,150,Vivek Chatterjee,HR,Kolkata,22.0,51391,0,7,8,2019-11-20

In [19]:
df.shape
## (100, 10)--> output

(100, 10)

In [20]:
df.dtypes ## what kind of data stored in each column

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [21]:
df.info() ## what is the overall structure and where are values  missing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [22]:
df.describe() ## used to taking basics stats in our table

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [55]:
df.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Salary  2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [56]:
df.isnull()

    Name  Salary
0  False   False
1  False   False

In [2]:
import pandas as pd
df = pd.read_csv("student_info - student_info.csv")
df.head(20)

,Student_ID,Name,Age,Gender,Department,Semester,Attendance_Percentage,Internal_Marks,CGPA,City,Scholarship
0,STU001,Arjun Sharma,NaN,Female,Data Science,4,97.8,42.0,7.79,Mangaluru,Yes
1,STU002,Arjun Shetty,24.0,Female,ISE,2,62.0,21.7,9.26,Chennai,Yes
2,STU003,Aarav Reddy,21.0,Male,CSE,8,86.9,20.6,9.83,Mangaluru,No
3,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No
4,STU005,Ananya Singh,21.0,Male,EEE,2,78.6,33.0,6.10,Mysuru,Yes
5,STU006,Aadhya Reddy,20.0,Male,EEE,7,61.3,NaN,6.51,Tumakuru,Yes
6,STU007,Kavya Iyer,23.0,Male,Mechanical,6,90.3,26.0,7.33,Mysuru,NaN
7,STU008,Riya Naidu,25.0,Female,Data Science,1,57.1,38.2,NaN,Mysuru,Yes
8,STU009,Rahul Joshi,24.0,Male,ISE,2,97.7,49.0,8.95,Mangaluru,Yes
9,STU010,Aadhya Singh,18.0,Male,EEE,2,59.4,40.5,6.92,NaN,No
10,STU011,Diya Patel,24.0,Female,ISE,4,77.3,21.0,9.50,Hubballi,Yes
11,STU012,Sai Nair,21.0,Male,Data Science,2,84.8,29.4,7.36,Belagavi,Yes
12,STU013,Rahul Kulkarni,19.0,Male,EEE,4,63.3,49.1,8.76,Chennai,No
13,STU014,Aditya Patel,19.0,Female,EEE,2,95.3,37.9,9.57,Mangaluru,No
14,STU015,Aadhya Naidu,25.0,Female,Civil,6,63.8,21.4,6.29,Hubballi,No
15,STU016,Vihaan Patel,25.0,Female,ECE,5,67.2,44.9,6.46,Chennai,No
16,STU017,Diya Patel,21.0,Other,AIML,4,79.4,24.2,8.91,Hyderabad,Yes
17,STU018,Vivaan Kulkarni,18.0,Male,AIML,1,99.4,43.2,5.59,Chennai,Yes
18,STU019,Aadhya Gupta,25.0,Female,Civil,7,91.7,41.2,8.51,Tumakuru,Yes
19,STU020,Arjun Shetty,18.0,Female,ECE,3,58.3,30.8,5.14,Belagavi,Yes

In [3]:
df[["CGPA","Age"]].isnull().sum()

CGPA    16
Age     12
dtype: int64

In [6]:
import pandas as pd 
df = pd.read_csv("student_info - student_info.csv")
df

,Student_ID,Name,Age,Gender,Department,Semester,Attendance_Percentage,Internal_Marks,CGPA,City,Scholarship
0,STU001,Arjun Sharma,NaN,Female,Data Science,4,97.8,42.0,7.79,Mangaluru,Yes
1,STU002,Arjun Shetty,24.0,Female,ISE,2,62.0,21.7,9.26,Chennai,Yes
2,STU003,Aarav Reddy,21.0,Male,CSE,8,86.9,20.6,9.83,Mangaluru,No
3,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No
4,STU005,Ananya Singh,21.0,Male,EEE,2,78.6,33.0,6.10,Mysuru,Yes
...,...,...,...,...,...,...,...,...,...,...,...
250,STU149,Kiran Joshi,25.0,Female,Mechanical,4,70.6,46.9,7.11,Belagavi,No
251,STU220,Vivaan Gupta,19.0,Male,NaN,7,84.7,20.8,5.72,Belagavi,No
252,STU095,Kiran Joshi,19.0,Female,Mechanical,2,56.0,NaN,6.05,Tumakuru,Yes
253,STU085,Ananya Rao,23.0,Female,ISE,6,86.7,34.2,5.04,Hubballi,Yes
254,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No

In [11]:
df.dropna()
df
df = df.dropna()
df

,Student_ID,Name,Age,Gender,Department,Semester,Attendance_Percentage,Internal_Marks,CGPA,City,Scholarship
1,STU002,Arjun Shetty,24.0,Female,ISE,2,62.0,21.7,9.26,Chennai,Yes
2,STU003,Aarav Reddy,21.0,Male,CSE,8,86.9,20.6,9.83,Mangaluru,No
3,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No
4,STU005,Ananya Singh,21.0,Male,EEE,2,78.6,33.0,6.10,Mysuru,Yes
8,STU009,Rahul Joshi,24.0,Male,ISE,2,97.7,49.0,8.95,Mangaluru,Yes
...,...,...,...,...,...,...,...,...,...,...,...
245,STU246,Diya Shetty,19.0,Female,Civil,1,89.7,23.2,4.91,Tumakuru,No
247,STU248,Meera Nair,24.0,Male,ECE,3,91.9,44.0,8.32,Chennai,No
250,STU149,Kiran Joshi,25.0,Female,Mechanical,4,70.6,46.9,7.11,Belagavi,No
253,STU085,Ananya Rao,23.0,Female,ISE,6,86.7,34.2,5.04,Hubballi,Yes
254,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No

In [13]:
x.shape

(157, 11)

In [14]:
x.isnull()

,Student_ID,Name,Age,Gender,Department,Semester,Attendance_Percentage,Internal_Marks,CGPA,City,Scholarship
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
245,False,False,False,False,False,False,False,False,False,False,False
247,False,False,False,False,False,False,False,False,False,False,False
250,False,False,False,False,False,False,False,False,False,False,False
253,False,False,False,False,False,False,False,False,False,False,False
254,False,False,False,False,False,False,False,False,False,False,False

In [15]:
x.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Gender                   0
Department               0
Semester                 0
Attendance_Percentage    0
Internal_Marks           0
CGPA                     0
City                     0
Scholarship              0
dtype: int64

In [16]:
x[x["Age"].isnull()]

Empty DataFrame
Columns: [Student_ID, Name, Age, Gender, Department, Semester, Attendance_Percentage, Internal_Marks, CGPA, City, Scholarship]
Index: []

In [17]:
df[df["Age"].isnull()]

Empty DataFrame
Columns: [Student_ID, Name, Age, Gender, Department, Semester, Attendance_Percentage, Internal_Marks, CGPA, City, Scholarship]
Index: []

In [19]:
df.dropna(subset=['CGPA','Age'])

,Student_ID,Name,Age,Gender,Department,Semester,Attendance_Percentage,Internal_Marks,CGPA,City,Scholarship
1,STU002,Arjun Shetty,24.0,Female,ISE,2,62.0,21.7,9.26,Chennai,Yes
2,STU003,Aarav Reddy,21.0,Male,CSE,8,86.9,20.6,9.83,Mangaluru,No
3,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No
4,STU005,Ananya Singh,21.0,Male,EEE,2,78.6,33.0,6.10,Mysuru,Yes
8,STU009,Rahul Joshi,24.0,Male,ISE,2,97.7,49.0,8.95,Mangaluru,Yes
...,...,...,...,...,...,...,...,...,...,...,...
245,STU246,Diya Shetty,19.0,Female,Civil,1,89.7,23.2,4.91,Tumakuru,No
247,STU248,Meera Nair,24.0,Male,ECE,3,91.9,44.0,8.32,Chennai,No
250,STU149,Kiran Joshi,25.0,Female,Mechanical,4,70.6,46.9,7.11,Belagavi,No
253,STU085,Ananya Rao,23.0,Female,ISE,6,86.7,34.2,5.04,Hubballi,Yes
254,STU004,Rahul Nair,21.0,Female,CSE,6,64.6,25.5,5.51,Hubballi,No

In [25]:
df["Age"] = df["Age"].fillna(0)
df["Age"]

C:\Users\samee\AppData\Local\Temp\ipykernel_19676\116719855.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].fillna(0)

1      24.0
2      21.0
3      21.0
4      21.0
8      24.0
       ...
245    19.0
247    24.0
250    25.0
253    23.0
254    21.0
Name: Age, Length: 157, dtype: float64