WHY DO WE NEED PANDA

In [45]:
import numpy as np 
import pandas as pd

Get a data set

In [46]:
a = [1,2,3,4,5,6] ## list

In [47]:
## converting list into a series 
s = pd.Series(a)
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [48]:
d = {"Aman" : 68, "rohan":34, "Akarsh" : 89}
s = pd.Series(d)
s

Aman      68
rohan     34
Akarsh    89
dtype: int64

In [51]:
df = pd.DataFrame([d])
df

   Aman  rohan  Akarsh
0    68     34      89

In [52]:
pd.DataFrame({
    "Name":["Aman","Riya"],
    "salary":[10000,500000]
})

   Name  salary
0  Aman   10000
1  Riya  500000

LOAD DATA IN CSV FILE

In [54]:
df = pd.read_csv("employees_100.csv")
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [55]:
df.head() ## SHOWS STARTING 5

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [56]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [60]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
9,101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [64]:
df.shape
## (100, 10)--> output

(100, 10)

In [65]:
df.dtypes ## what kind of data stored in each column

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [67]:
df.info() ## what is the overall structure and where are values  missing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB