Selecting and filtering data

WHy Do we need this

Most of the time you dont need the whole dataset s -- you need specific col and row or only the records matching a conditions

In [82]:
import numpy as np 
import pandas as pd
df = pd.read_csv("employees_100.csv")
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [83]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

SELECTING SINGLE COLUMN

In [84]:
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: object

SELECTING MULTIPLE COLUMN

In [85]:
## for multiple alwayse use 2 brakets 
df[['name','salary']].head()

             name salary
0    Swati Kapoor  70719
1  Kavya Malhotra  77058
2    Manish Desai  69911
3        Neha Das  69993
4       Isha Nair  88216

SELECTING THE ROWS

INTERACTIVE .loc[] vd ILOC[]

In [86]:
# location and index location iLOC[]
df = df.set_index("employee_id")
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [87]:
df.loc[[184]]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02

In [88]:
df.loc[[184 , 154]]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05

In [89]:
## slice out of the row 
df.loc[184 : 154]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05

In [90]:
##iloc 
## works in the indexing 
df.iloc[1:5]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [91]:
df.loc[154:145][["name","city","age" , "salary"]]

                       name       city   age salary
employee_id
154          Kavya Malhotra     Mumbai   NaN  77058
171            Manish Desai  Hyderabad  23.0  69911
146                Neha Das       Pune  28.0  69993
145               Isha Nair        NaN  32.0  88216

In [92]:
##with the help of the iloc function 
df.iloc[1:5][["name","city","age" , "salary"]]

                       name       city   age salary
employee_id
154          Kavya Malhotra     Mumbai   NaN  77058
171            Manish Desai  Hyderabad  23.0  69911
146                Neha Das       Pune  28.0  69993
145               Isha Nair        NaN  32.0  88216

In [98]:
df[df['projects_completed'] >10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
119,Ritu Desai,Marketing,Pune,22.0,55321,0,6,18,2020-02-18
131,Priya Malhotra,Marketing,Hyderabad,25.0,55295,1,7,12,2022-02-13
174,Divya Chatterjee,Finance,Kolkata,24.0,58374,1,3,12,2018-09-21
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
191,Neha Malhotra,Marketing,Mumbai,29.0,64944,2,10,18,2023-10-05
177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
189,Anjali Shah,Marketing,Delhi,33.0,56321,6,7,14,2022-08-14
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
117,Pooja Malhotra,engineering,Kolkata,24.0,84255,1,8,19,2021-12-05
196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08
120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
139,Rahul Malhotra,Marketing,Hyderabad,23.0,60203,2,6,15,2022-09-17
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [106]:
df2  = df[df['age'] >40]
df2

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [108]:
## give me people who are working in the finance and there age is greater than 30 
df[df['department'] == "Finance"]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
174,Divya Chatterjee,Finance,Kolkata,24.0,58374,1,3,12,2018-09-21
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
118,Rajesh Nair,Finance,Hyderabad,26.0,67464,1,5,9,2019-01-26
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
153,Pooja Das,Finance,Mumbai,27.0,64112,1,4,6,2019-08-25

In [123]:
df[((df['department'] =="Finance") | (df['department'] == "Sales" )) & (df
    ['age'] > 30) & (df['experience']>5)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19

USE FUL FILTERING METHOD

In [126]:
df[df["name"].str.contains("Verma")]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10