In [53]:
import numpy as np 
import pandas as pd
df = pd.read_csv("employees_100.csv")
df.head()
df.duplicated(subset=["employee_id"]).sum()
df.drop_duplicates(subset=["employee_id"],keep="first",inplace=True)
## Top and bottom records

 WHY DO WE NEED THIS

After analyzing data, you usually want the extremes — the highest, lowest, best, or worst performing records, not the whole table in whatever order it happened to load in.

SORTING VALUES

In [54]:
##sort the employee id 
df.sort_values(by = "employee_id")
# df.sort_values(by = "salary") ## its showing the shadow copy 
## if we want data will work with this method so use inplace = "True"  save the value

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
9,101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
87,103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19
51,104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
15,105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
...,...,...,...,...,...,...,...,...,...,...
90,192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
34,194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
78,195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
43,196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08

In [55]:
df.sort_values(by = "salary" , ascending =False)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255,1,8,19,2021-12-05
...,...,...,...,...,...,...,...,...,...,...
23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06

In [56]:
result = df.sort_values(by = ['department','salary'] , ascending=[True,False] )
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
16,177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
27,162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
11,131,Priya Malhotra,Marketing,Hyderabad,25.0,55295,1,7,12,2022-02-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
...,...,...,...,...,...,...,...,...,...,...
62,155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
81,185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
32,186,Rohan Kapoor,NaN,Pune,36.0,65152,8,7,4,2020-02-15
61,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07

In [57]:
 df['department'].unique()

array(['Data Science', 'engineering', 'Engineering', 'Sales', 'HR',
       'Marketing', ' Marketing ', 'Finance', ' Finance ', ' HR ', nan,
       'FINANCE', 'SALES', 'MARKETING'], dtype=object)

In [58]:
df['department'] = df['department'].str.strip().str.title()
df['department'].unique()

array(['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing',
       'Finance', nan], dtype=object)

In [59]:
result = df.sort_values(by = ['department','salary'] , ascending=[True,False] )
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
59,190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
...,...,...,...,...,...,...,...,...,...,...
62,155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
81,185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
32,186,Rohan Kapoor,NaN,Pune,36.0,65152,8,7,4,2020-02-15
61,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07

RANKING

In [60]:
df['salary_rank'] = df['salary'].rank()

In [61]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02,63.0
1,154,Kavya Malhotra,Engineering,Mumbai,NaN,77058,1,8,8,2024-02-05,76.0
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24,61.0
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13,62.0
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25,88.0
...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,Marketing,Chennai,22.0,55740,0,5,22,2020-04-22,15.0
96,172,Neha Desai,Hr,Chennai,22.0,52250,0,5,7,2020-11-14,7.0
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN
98,193,Priya Nayak,Hr,NaN,23.0,56821,3,9,16,2019-08-07,21.0
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25,59.0

In [62]:
df.sort_values(by="salary_rank",ascending=True)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
26,141,Manish Kulkarni,Hr,Chennai,27.0,"45,835",3,8,13,2022-07-21,1.0
36,167,Meera Malhotra,Hr,Hyderabad,31.0,48822,4,5,4,2022-06-24,2.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693,0,4,7,2018-08-27,3.0
67,169,Swati Chatterjee,Hr,Pune,33.0,49801,3,6,11,2021-08-20,4.0
7,181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05,5.0
...,...,...,...,...,...,...,...,...,...,...,...
23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,NaN
45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27,NaN
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25,NaN
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07,NaN
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN

In [74]:
df.nlargest(5 ,"salary_rank")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25,88.0
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26,87.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05,86.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07,85.0
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255,1,8,19,2021-12-05,84.0