In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

df = pd.read_csv("scaling_pandas_student_dataset.csv")
df

,Student_ID,Age,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Internal_Marks,CGPA
0,STU001,24,17,91.0,79,62,9.94
1,STU002,21,7,85.5,61,78,7.14
2,STU003,22,10,80.8,60,58,6.92
3,STU004,24,12,60.8,81,92,8.40
4,STU005,20,31,91.5,90,51,6.09
...,...,...,...,...,...,...,...
245,STU246,23,20,79.7,85,66,5.30
246,STU247,18,6,79.0,88,54,6.24
247,STU248,18,32,71.0,58,77,5.80
248,STU249,18,36,95.2,59,94,9.36
249,STU250,20,31,60.8,86,82,6.10

In [3]:
minimum = df["Study_Hours_Per_Week"].min()
print(minimum)

5

In [4]:
maximum = df["Study_Hours_Per_Week"].max()
print(maximum)

40

In [5]:
df["Study_Hours_Scaled"] = (
    (df["Study_Hours_Per_Week"] - minimum) /
    (maximum - minimum)
)

In [8]:
df[["Study_Hours_Per_Week" , "Study_Hours_Scaled"]].head(10)

   Study_Hours_Per_Week  Study_Hours_Scaled
0                    17            0.342857
1                     7            0.057143
2                    10            0.142857
3                    12            0.200000
4                    31            0.742857
5                    13            0.228571
6                    37            0.914286
7                    28            0.657143
8                    19            0.400000
9                    36            0.885714

In [9]:
df.columns

Index(['Student_ID', 'Age', 'Study_Hours_Per_Week', 'Attendance_Percentage',
       'Assignment_Score', 'Internal_Marks', 'CGPA', 'Study_Hours_Scaled'],
      dtype='object')

In [16]:
import pandas as pd 
df = pd.read_csv("scaling_pandas_student_dataset.csv")
numeric_columns = df.select_dtypes(include="number").columns
df[numeric_columns] = (
    (df[numeric_columns] - df[numeric_columns].min()) /
    (df[numeric_columns].max() - df[numeric_columns].min())
)

In [17]:
df.head(20)

,Student_ID,Age,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Internal_Marks,CGPA
0,STU001,0.857143,0.342857,0.800905,0.676923,0.492308,0.989919
1,STU002,0.428571,0.057143,0.676471,0.400000,0.738462,0.425403
2,STU003,0.571429,0.142857,0.570136,0.384615,0.430769,0.381048
3,STU004,0.857143,0.200000,0.117647,0.707692,0.953846,0.679435
4,STU005,0.285714,0.742857,0.812217,0.846154,0.323077,0.213710
5,STU006,1.000000,0.228571,0.821267,0.953846,0.384615,0.951613
6,STU007,0.571429,0.914286,0.624434,0.723077,0.415385,0.786290
7,STU008,0.571429,0.657143,0.821267,0.923077,0.738462,0.084677
8,STU009,0.857143,0.400000,0.649321,0.384615,0.738462,0.415323
9,STU010,0.142857,0.885714,0.196833,0.538462,0.292308,0.881048
10,STU011,0.285714,0.885714,0.264706,0.000000,0.953846,0.945565
11,STU012,0.857143,0.657143,0.205882,0.107692,0.923077,0.465726
12,STU013,0.285714,0.314286,0.371041,0.784615,0.738462,0.612903
13,STU014,0.285714,0.028571,0.027149,0.707692,0.000000,0.163306
14,STU015,1.000000,0.057143,0.615385,0.846154,0.184615,0.993952
15,STU016,0.571429,0.457143,0.328054,0.200000,0.769231,0.227823
16,STU017,0.428571,0.028571,0.653846,0.415385,0.846154,0.943548
17,STU018,1.000000,0.028571,0.377828,0.015385,0.938462,0.649194
18,STU019,1.000000,0.771429,0.680995,0.384615,0.476923,0.606855
19,STU020,0.285714,0.628571,0.332579,0.200000,0.446154,0.510081

In [34]:
import pandas as pd 
df = pd.read_csv("scaling_pandas_student_dataset.csv")
df

,Student_ID,Age,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Internal_Marks,CGPA
0,STU001,24,17,91.0,79,62,9.94
1,STU002,21,7,85.5,61,78,7.14
2,STU003,22,10,80.8,60,58,6.92
3,STU004,24,12,60.8,81,92,8.40
4,STU005,20,31,91.5,90,51,6.09
...,...,...,...,...,...,...,...
245,STU246,23,20,79.7,85,66,5.30
246,STU247,18,6,79.0,88,54,6.24
247,STU248,18,32,71.0,58,77,5.80
248,STU249,18,36,95.2,59,94,9.36
249,STU250,20,31,60.8,86,82,6.10

In [35]:
mean = df["Study_Hours_Per_Week"].mean()
print(mean)

23.668

In [36]:
stand_dev = df["Study_Hours_Per_Week"].std()
print(stand_dev)

10.941877110386278

In [37]:
df["Study_Hours_Z"] = (
    (df['Study_Hours_Per_Week'] - mean) / stand_dev
)

In [38]:
df[["Study_Hours_Per_Week" , "Study_Hours_Z"]].head(10)

   Study_Hours_Per_Week  Study_Hours_Z
0                    17      -0.609402
1                     7      -1.523322
2                    10      -1.249146
3                    12      -1.066362
4                    31       0.670086
5                    13      -0.974970
6                    37       1.218438
7                    28       0.395910
8                    19      -0.426618
9                    36       1.127046

In [41]:
df["Assignment_Score"].isnull().sum()

np.int64(0)

In [43]:
df.columns

Index(['Student_ID', 'Age', 'Study_Hours_Per_Week', 'Attendance_Percentage',
       'Assignment_Score', 'Internal_Marks', 'CGPA', 'Study_Hours_Z'],
      dtype='object')

In [44]:
df["CGPA"]

0      9.94
1      7.14
2      6.92
3      8.40
4      6.09
       ...
245    5.30
246    6.24
247    5.80
248    9.36
249    6.10
Name: CGPA, Length: 250, dtype: float64

In [45]:
import pandas as pd 
df = pd.read_csv("scaling_pandas_student_dataset.csv")
df

,Student_ID,Age,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Internal_Marks,CGPA
0,STU001,24,17,91.0,79,62,9.94
1,STU002,21,7,85.5,61,78,7.14
2,STU003,22,10,80.8,60,58,6.92
3,STU004,24,12,60.8,81,92,8.40
4,STU005,20,31,91.5,90,51,6.09
...,...,...,...,...,...,...,...
245,STU246,23,20,79.7,85,66,5.30
246,STU247,18,6,79.0,88,54,6.24
247,STU248,18,32,71.0,58,77,5.80
248,STU249,18,36,95.2,59,94,9.36
249,STU250,20,31,60.8,86,82,6.10

In [47]:
numeric_columns = df.select_dtypes(include="number").columns
df[numeric_columns]  = (
    (df[numeric_columns] - df[numeric_columns].mean())/
    df[numeric_columns].std()
)

In [48]:
df.head(10)

,Student_ID,Age,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Internal_Marks,CGPA
0,STU001,1.077978,-0.609402,1.049819,0.629644,-0.017307,1.595822
1,STU002,-0.256153,-1.523322,0.609472,-0.301476,0.837347,-0.276330
2,STU003,0.188557,-1.249146,0.233176,-0.353205,-0.230970,-0.423427
3,STU004,1.077978,-1.066362,-1.368086,0.733102,1.585169,0.566138
4,STU005,-0.700863,0.670086,1.089851,1.198662,-0.604881,-0.978386
5,STU006,1.522688,-0.974970,1.121876,1.560764,-0.391218,1.468783
6,STU007,0.188557,1.218438,0.425327,0.784831,-0.284386,0.920510
7,STU008,0.188557,0.395910,1.121876,1.457306,0.837347,-1.406306
8,STU009,1.077978,-0.426618,0.513396,-0.353205,0.837347,-0.309761
9,STU010,-1.145574,1.127046,-1.087865,0.164084,-0.711713,1.234764

In [49]:
import pandas as pd
df = pd.read_csv("scaling_pandas_student_dataset.csv")
numeric_columns = [
    "Age","Study_Hours_Per_Week" , "Attendance_Percentage" , "Assignment_Score" , "Internal_Marks" , "CGPA"
]

['Age', 'Study_Hours_Per_Week', 'Attendance_Percentage', 'Assignment_Score', 'Internal_Marks', 'CGPA']